Changelog:
<div style='text-align:left;width:700;'>
<br><b>4/8/2014 </b>
<br>- Consolidated world regenration to generatenew().
<br>- Added a function to force movement if it did not happen last turn.
<br><b>3/27/2014 </b>
<br>- Remapping the path that ANTS learn about changes to WORLD.
<br>- Some misc stylistic changes to improve coding standards.
<br>- Added FSM to Nests, fixing spawn bug.
<br>- Dead ants now drop carried food.
<br>- Ants can now both attack and defend.
<br><b>3/25/2014 </b>
<br>- Optimization to pathfinding(it was taking way too long. Simplified it).
<br><b>3/23/2014 </b>
<br>- Changed Ants color schemes to go easy on my eye strain.
<br>- Append turn log at the bottom of the page.
<br>- Increaced maximum number of food items on screen at one time from 10 to 25.
<br>- Stamina is now shown, and type is in bold.
<br>- When ants die, they leave a corpse other ants can take. Yay canabalism!
<br>- When ant nests have no more ants, they now crumble and dissapear.
<br>- Dissapearing ant nests leave some yummy 10 quality food!
<br>- Foods are now colored pink. Because I hate white.
</div>