1). Every 5 turns a piece of food is created.<br>
2). For every 10 'quality' a food imparts to the nest, one ant is generated.<br>
3). Only one ant may carry a piece of food at a time.<br>
4). Each ant will target the closest piece of food.<br>
5). Each refresh represents one turn.<br>
6). Ants have 50 stamina to start. At 0, they die.<br>
7). Ants get 10 stamina for retrieving and dropping off food.<br>
8). Ants loose 1 stamina per turn.<br>
9). When ants die, they leave behind a corpse worth .5 food.<br>
10). The homward-bound ant will always yeild to the ant searching for food<br>
either to the left or the right.